name: Windows Build (LZSR)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compilazione con Make
      # Questa riga dice a GitHub di entrare nella cartella LZSR
      working-directory: ./LZSR
      run: |
        mingw32-make

    - name: Salva l'eseguibile
      uses: actions/upload-artifact@v4
      with:
        name: LZSR-Windows-Exe
        # Anche qui indichiamo il percorso corretto del file prodotto
        path: LZSR/LZSR.exe
